FROM python:3.10
WORKDIR /app

COPY api/apis.py api/requirements.txt api/.flaskenv ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["waitress-serve", "--call", "api:app"]
