# Why don't I have to create container for this Dockerfile?
FROM nginx
# copy our version of ./default.conf into some wacky path
# not too sure low level of this, but we are changing the 
# normal default.conf
COPY ./default.conf /etc/nginx/conf.d/default.conf